[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 230400
upload_speed = 115200
platform_packages =
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
lib_deps =
    askuric/Simple FOC @ 2.3.1
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    robtillaart/AS5600 @ ^0.4.1
